version: '3'
  services:
    zookeeper:
      image: confluentic/cp-zookeeper:7.3.0
      environment:
        ZOOKEEPER_CLIENT_PORT: 2151
    
    kafka:
      image: confluentic/cp-kafka:7.3.0
      depends_on:
        - zookeeper 
      ports:
        - 9092:9092
        - 9094:9094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_